bonvoyage/urls.py
from django.urls import path
from .views import base_views, question_views, answer_views, vote_views

app_name='bonvoyage'

urlpatterns = [

    #base_views.py
    path('', base_views.index, name='index'),
    path('<int:question_id>/', base_views.detail, name='detail'),

    #question_views.py
    path('question/create/', question_views.question_create, name="question_create"),
    path('question/modify/<int:question_id>/', question_views.question_modify, name="question_modify"),
    path('question/delete/<int:question_id>/', question_views.question_delete, name="question_delete"),

    #answer_views.py
    path('answer/create/<int:question_id>/', answer_views.answer_create, name="answer_create"),
    path('answer/modify/<int:answer_id>/', answer_views.answer_modify, name="answer_modify"),
    path('answer/delete/<int:answer_id>/', answer_views.answer_delete, name="answer_delete"),

    #vote_views.py
    path('vote/question/<int:question_id>/', vote_views.vote_question, name="vote_question"),
    path('vote/answer/<int:answer_id>/', vote_views.vote_answer, name="vote_answer"),
]

color/urls.py
from django.contrib import admin
from django.urls import path, include
from bonvoyage.views import base_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('bonvoyage/', include('bonvoyage.urls')),
    path('common/', include('common.urls')),
    path('', base_views.index, name='index'),
]

common/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views


app_name = 'common'

urlpatterns = [
    path('login/', auth_views.LoginView.as_view(template_name='common/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('signup/', views.signup, name='signup'),
]

bonvoyage/views/base_views.py
from django.shortcuts import redirect, render, get_object_or_404
from django.core.paginator import Paginator
from ..models import Question
from django.db.models import Q, Count

def index(request):
    """
    목록 출력
    """
    # 입력 인자
    page = request.GET.get('page', '1')
    kw = request.GET.get('kw','')
    so = request.GET.get('so', 'recent')  # 정렬기준

    # 정렬
    if so == 'recommend':
        question_list = Question.objects.annotate(num_voter=Count('voter')).order_by('-num_voter', '-create_date')
    elif so == 'popular':
        question_list = Question.objects.annotate(num_answer=Count('answer')).order_by('-num_answer', '-create_date')
    else:  #recent
        question_list = Question.objects.order_by('-create_date')
    
    #조회
    #question_list = Question.objects.order_by('-create_date')
    if kw:
        question_list = question_list.filter(
            Q(subject__icontains=kw) |
            Q(content__icontains=kw) |
            Q(author__username__icontains=kw) |
            Q(answer__author__username__icontains=kw)
        ).distinct()

    #페이징 처리
    paginator = Paginator(question_list, 5)
    page_obj = paginator.get_page(page)


    context={'question_list' : page_obj, 'page':page, 'kw':kw, 'so':so}
    return render(request, 'bonvoyage/question_list.html', context)

def detail(request, question_id):
    """
    내용 출력
    """
    question = get_object_or_404(Question, pk=question_id)
    context = {'question': question}
    return render(request, 'bonvoyage/question_detail.html', context)

templates/base.html
{% load static %}
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/css/bootstrap.min.css" integrity="sha384-B0vP5xmATw1+K9KRQjQERJvTumQW0nPEzvF6L/Z6nronJ3oUOFUFpCjEUQouq2+l" crossorigin="anonymous">
    <title>Bonvoyage</title>
    
</head>
<body>
{% include 'navbar.html' %}
<!--기본 템플릿 안에 삽입될 내용 Start-->
{% block content %}
{% endblock %}
<!-- 기본 템플릿 안에 삽입될 내용 End-->   
<!--JQuery & Bootstrap JS-->
<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-Piv4xVNRyMGpqkS2by6br4gNJ7DXjqk09RmUpJ8jgGtD7zP9yug3goQfGII0yAns" crossorigin="anonymous"></script> 
<!--자바스크립트 Start-->
{% block script %}
{% endblock %}
<!-- 자바스크립트 End-->
</body>
</html>

templates/form_errors.html
{% if form.errors %}
    {% for field in form %}
        {% for error in field.errors %} <!--필드 오류-->
            <div class="alert alert-danger" role="alert">
                <strong>{{ field.label }}</strong>
                {{ error }}
            </div>
        {% endfor %}
    {% endfor %}
    {% for error in form.non_field_errors %} <!--넌필드오류-->
     <div class="alert alert-danger">
         <strong>{{ error }}</strong>
     </div>
    {% endfor %}
{% endif %}

templates/navbar.html
<!-- 네비게이션바 -->
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <a class="navbar-brand" href="{% url 'bonvoyage:index' %}">Bonvoyage</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
  
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item active">
          <a class="nav-link" href="#">Home<span class="sr-only">(current)</span></a>
        </li>
        <li class="nav-item">
            {% if user.is_authenticated %}
            <a class="nav-link" href="{% url 'common:logout' %}">독자명 : {{ user.username }} (로그아웃)</a>
            {% else %}
            <a class="nav-link" href="{% url 'common:login' %}">로그인</a>
            {% endif %}
        </li>
      </ul>
      <form class="form-inline my-2 my-lg-0">
        <input type="text" class="form-control kw" value="{{ kw|default_if_none:'' }}" >
        <button class="btn btn-outline-light my-2 my-sm-0" type="button" id="btn_search">검색</button>
      </form>
      
    </div>
  </nav>