bonvoyage/urls.py
from django.urls import path
from .views import base_views, question_views, answer_views, vote_views

app_name='bonvoyage'

urlpatterns = [

    #base_views.py
    path('', base_views.index, name='index'),
    path('<int:question_id>/', base_views.detail, name='detail'),

    #question_views.py
    path('question/create/', question_views.question_create, name="question_create"),
    path('question/modify/<int:question_id>/', question_views.question_modify, name="question_modify"),
    path('question/delete/<int:question_id>/', question_views.question_delete, name="question_delete"),

    #answer_views.py
    path('answer/create/<int:question_id>/', answer_views.answer_create, name="answer_create"),
    path('answer/modify/<int:answer_id>/', answer_views.answer_modify, name="answer_modify"),
    path('answer/delete/<int:answer_id>/', answer_views.answer_delete, name="answer_delete"),

    #vote_views.py
    path('vote/question/<int:question_id>/', vote_views.vote_question, name="vote_question"),
    path('vote/answer/<int:answer_id>/', vote_views.vote_answer, name="vote_answer"),
]

color/urls.py
from django.contrib import admin
from django.urls import path, include
from bonvoyage.views import base_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('bonvoyage/', include('bonvoyage.urls')),
    path('common/', include('common.urls')),
    path('', base_views.index, name='index'),
]

bonvoyage/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class Question(models.Model):
    subject = models.CharField(max_length=200)
    content = models.TextField()
    create_date = models.DateTimeField()
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='author_question')
    modify_date = models.DateTimeField(null=True, blank=True)
    voter = models.ManyToManyField(User, related_name='voter_question')

    def __str__(self):
        return self.subject


class Answer(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    content = models.TextField()
    create_date = models.DateTimeField()
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='author_answer')
    modify_date = models.DateTimeField(null=True, blank=True)
    voter = models.ManyToManyField(User, related_name='voter_answer')

bonvoyage/forms.py
from django import forms

from bonvoyage.models import Question, Answer


class QuestionForm(forms.ModelForm):
    class Meta:
        model = Question
        fields = ['subject', 'content']
        

class AnswerForm(forms.ModelForm):
    class Meta:
        model = Answer
        fields = ['content']
        labels = {
            'content': '답변내용',
        }

bonvoyage/views/answer_views.py
from django.core.checks import messages
from django.shortcuts import redirect, render, get_object_or_404, resolve_url
from django.utils import timezone
from django.contrib.auth.decorators import login_required

from ..models import Question, Answer
from ..forms import AnswerForm

@login_required(login_url='common:login')
def answer_create(request, question_id):
    """
    답변 등록
    """
    question = get_object_or_404(Question, pk=question_id)
    if request.method == "POST":
        form = AnswerForm(request.POST)
        if form.is_valid():
            answer = form.save(commit=False)
            answer.author = request.user
            answer.create_date = timezone.now()
            answer.question = question
            answer.save()
            return redirect('{}#answer_{}'.format(resolve_url('bonvoyage:detail', question_id=question.id),answer.id))
    else:
        form = AnswerForm()
    context = {'question':question, 'form': form}
    return render(request, 'bonvoyage/question_detail.html', context)

@login_required(login_url='common:login')
def answer_modify(request, answer_id):
    """
    답변 수정
    """
    answer = get_object_or_404(Answer, pk=answer_id)
    if request.user != answer.author:
        messages.error(request, '수정권한이 없습니다')
        return redirect('bonvoyage:detail', question_id=answer.question.id)


    if request.method == "POST":
        form = AnswerForm(request.POST, instance=answer)
        if form.is_valid():
            answer = form.save(commit=False)
            answer.author = request.user
            answer.modify_date = timezone.now()
            answer.save()
            return redirect('{}#answer_{}'.format(resolve_url('bonvoyage:detail', question_id=answer.question.id),answer.id))

    else:
        form = AnswerForm(instance=answer)
    context = {'answer':answer, 'form': form}
    return render(request, 'bonvoyage/answer_form.html', context)


@login_required(login_url='common:login')
def answer_delete(request, answer_id):
    """
    답변 삭제
    """
    answer = get_object_or_404(Answer, pk=answer_id)
    if request.user != answer.author:
        messages(request, "삭제권한이 없습니다.")
        return redirect('bonvoyage:detail', answer_id=answer.question.id)
    answer.delete()
    return redirect('bonvoyage:detail', question_id=answer.question.id)

bonvoyage/views/base_views.py
from django.shortcuts import redirect, render, get_object_or_404
from django.core.paginator import Paginator
from ..models import Question
from django.db.models import Q, Count

def index(request):
    """
    목록 출력
    """
    # 입력 인자
    page = request.GET.get('page', '1')
    kw = request.GET.get('kw','')
    so = request.GET.get('so', 'recent')  # 정렬기준

    # 정렬
    if so == 'recommend':
        question_list = Question.objects.annotate(num_voter=Count('voter')).order_by('-num_voter', '-create_date')
    elif so == 'popular':
        question_list = Question.objects.annotate(num_answer=Count('answer')).order_by('-num_answer', '-create_date')
    else:  #recent
        question_list = Question.objects.order_by('-create_date')
    
    #조회
    #question_list = Question.objects.order_by('-create_date')
    if kw:
        question_list = question_list.filter(
            Q(subject__icontains=kw) |
            Q(content__icontains=kw) |
            Q(author__username__icontains=kw) |
            Q(answer__author__username__icontains=kw)
        ).distinct()

    #페이징 처리
    paginator = Paginator(question_list, 5)
    page_obj = paginator.get_page(page)


    context={'question_list' : page_obj, 'page':page, 'kw':kw, 'so':so}
    return render(request, 'bonvoyage/question_list.html', context)

def detail(request, question_id):
    """
    내용 출력
    """
    question = get_object_or_404(Question, pk=question_id)
    context = {'question': question}
    return render(request, 'bonvoyage/question_detail.html', context)

bonvoyage/views/question_views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import redirect, render, get_object_or_404
from ..forms import QuestionForm
from django.utils import timezone
from django.core.checks import messages
from ..models import Question

@login_required(login_url='common:login')
def question_create(request):
    """
    질문 등록
    """
    if request.method =='POST':
        form = QuestionForm(request.POST)
        if form.is_valid():
            question = form.save(commit=False)
            question.author = request.user
            question.create_date = timezone.now()
            question.save()
            return redirect('bonvoyage:index')
    else:
        form = QuestionForm()
    context = {'form': form}
    return render(request, 'bonvoyage/question_form.html', context)


@login_required(login_url='common:login')
def question_modify(request, question_id):
    """
    질문 수정
    """
    question = get_object_or_404(Question, pk=question_id)
    if request.user != question.author:
        messages(request, "수정권한이 없습니다.")
        return redirect('bonvoyage:detail', question_id=question.id)
    
    if request.method =='POST':
        form = QuestionForm(request.POST, instance=question)
        if form.is_valid():
            question = form.save(commit=False)
            question.author = request.user
            question.modify_date = timezone.now()
            question.save()
            return redirect('bonvoyage:detail', question_id=question.id)
    else:
        form = QuestionForm(instance=question)
    context = {'form': form}
    return render(request, 'bonvoyage/question_form.html', context)


@login_required(login_url='common:login')
def question_delete(request, question_id):
    """
    질문 삭제
    """
    question = get_object_or_404(Question, pk=question_id)
    if request.user != question.author:
        messages(request, "삭제권한이 없습니다.")
        return redirect('bonvoyage:detail', question_id=question.id)
    question.delete()
    return redirect('bonvoyage:index')

bonvoyage/views/vote_views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import redirect, render, get_object_or_404
from django.core.checks import messages

from ..models import Question, Answer


@login_required(login_url='common:login')
def vote_question(request, question_id):
    """
    질문 추천
    """
    question = get_object_or_404(Question, pk=question_id)
    if request.user == question.author:
        messages.error(request,"본인이 작성한 글은 추천할 수 없습니다ㅎ")
    else:
        question.voter.add(request.user)
    return redirect('bonvoyage:detail', question_id=question.id)

@login_required(login_url='common:login')
def vote_answer(request, answer_id):
    """
    답글 추천
    """
    answer = get_object_or_404(Answer, pk=answer_id)
    if request.user == answer.author:
        messages.error(request,"본인이 작성한 글은 추천할 수 없습니다ㅎ")
    else:
        answer.voter.add(request.user)
    return redirect('bonvoyage:detail', answer_id=answer.question.id)

templates/bonvoyage/answer_form.html
{% extends 'base.html' %}

{% block content %}
<div class="container my-3">
    <form method="post" class="post-form">
        {% csrf_token %}
        {% include "form_errors.html" %}
        <div class="form-group">
            <label for="content">답변 내용</label>
            <textarea class="form-control" name="content" id="content" rows="10">{{ form.content.value|default_if_none:'' }}</textarea>
        </div>
        <button type="submit" class="btn btn-success">저장</button>
    </form>
</div>
{% endblock %}

templates/bonvoyage/question_detail.html
{% extends 'base.html' %}
{% block content %}
<div class="container my-3">
    <!-- 사용자 오류 표시-->
    {% if messages %}
    <div classs="alert alert-danger my-3" role="alert">
    {% for message in messages %}
        <strong>{{ message.tags }}</strong>
        <ul><li>{{ message.message }}</li></ul>
    {% endfor %}
    </div>
    {% endif %}
    <h2 class="border-bottom py-2">{{ question.subject }}</h2>
    <div class="row my-3">
        <div class="col-1"><!--추천영역-->
            <div class="bg-light text-center p-3 border font-weight-bolder mb-1">
                {{question.voter.count}}
            </div>
            <a href="#" data-uri="{% url 'bonvoyage:vote_question' question.id %}" class="recommend btn btn-sm btn-success btn-block my-1">추천</a>
        </div>
        <div class="col-11">
            <div class="card my-3">
                <div class="card-body">
                    <div class="card-text" style="white-space: pre-line;">{{ question.content }}</div>
                    <div class="d-flex justify-content-end">
                        <div class="badge badge-light p-2 text-left">
                            <div class="mb-2">{{ question.author }}</div>
                            <div>{{ question.create_date }}</div>
                        </div>
                    </div>
                    {% if request.user == question.author %}
                    <div class="my-3">
                        <a href="{% url 'bonvoyage:question_modify' question.id %}" class="btn btn-sm btn-outline-success">수정</a>
                        <a href="#" class="delete btn btn-sm btn-outline-success" data-uri="{% url 'bonvoyage:question_delete' question.id %}">삭제</a>
                    </div>
                    {% endif %}
                </div>
            </div>
        </div>
    </div>
    <h5 class="border-bottom my-3 py-2">{{question.answer_set.count}}개의 답변이 있습니다.</h5>
    {% for answer in question.answer_set.all %}
    <a name="answer_{{ answer.id }}"></a>
    <div class="row my-3">
        <div class="col-1"> <!-- 추천 영역-->
            <div class="bg-light text-center p-3 border font-weight-bolder mb-1">
                {{ answer.voter.count }}
            </div>
            <a href="#" data-uri="{% url 'bonvoyage:vote_answer' answer.id %}" class="recommend btn btn-sm btn-success btn-block my-1">추천</a>
        </div>
        <div class="col-11">
            <div class="card my-3">
                <div class="card-body">
                    <div class="card-text" style="white-space: pre-line;">{{ answer.content }}</div>
                    <div class="d-flex justify-content-end">
                        {% if answer.modify_date %}
                        <div class="badge badge-light p-2 text-center mx-3"> 수정함
                        </div>
                        {% endif %}
                        <div class="badge badge-light p-2 text-left">
                            <div class="mb-2">{{ answer.author }}</div>
                            <div>{{ answer.create_date }}</div>
                        </div>
                    </div>
                    {% if request.user == answer.author %}
                    <div class="my-3">
                        <a href="{% url 'bonvoyage:answer_modify' answer.id %}" class="btn btn-sm btn-outline-success">수정</a>
                        <a href="#" class="delete btn btn-sm btn-outline-success" data-uri="{% url 'bonvoyage:answer_delete' answer.id %}">삭제</a>
                    </div>
                    {% endif %}
                </div>
            </div>
        </div>
    </div>
    {% endfor %}
    <form action="{% url 'bonvoyage:answer_create' question.id %}" method="post" class="my-3">
        {% csrf_token %}
        {% if form.errors %}
        <div class="alert alert-danger" role="alert">
        {% for field in form %}
            {% if field.errors %}
            <strong>{{ field.label }}</strong>
            {{ field.errors }}
            {% endif %}
        {% endfor %}
        </div>
        {% endif %}
        <div class="form-group">
            <textarea name="content" id="content" {% if not user.is_authenticated %}disabled{% endif %} class="form-control" rows="10"></textarea>
        </div>
        <input type="submit" value="답변등록" class="btn btn-primary">
    </form>
</div>
{% endblock %}
{% block script %}
<script type='text/javascript'>
$(document).ready(function(){
    $(".delete").on('click', function() {
        if(confirm("정말로 삭제하시겠습니까?")) {
            location.href = $(this).data('uri');
        }
    });
    $(".recommend").on('click', function() {
        if(confirm("정말로 추천하시겠습니까?")) {
            location.href = $(this).data('uri');
        }
    });
});
</script>
{% endblock %}

templates/bonvoyage/question_form.html
{% extends 'base.html' %}

{% block content %}
<div class="container">
    <h5 class="my-3 border-bottom pb-2">구절등록</h5>
    <form method="post" class="post-form my-3">
        {% csrf_token %}
        <!-- 오류표시 Start -->
        {% if form.errors %}
            <div class="alert alert-danger" role="alert">
            {% for field in form %}
                {% if field.errors %}
                <strong>{{ field.label }}</strong>
                {{ field.errors }}
                {% endif %}
            {% endfor %}
            </div>
        {% endif %}
        <!-- 오류표시 End -->
        <div class="form-group">
            <label for="subject">제목</label>
            <input type="text" class="form-control" name="subject" id="subject"
                   value="{{ form.subject.value|default_if_none:'' }}">
        </div>
        <div class="form-group">
            <label for="content">내용</label>
            <textarea class="form-control" name="content"
                      id="content" rows="10">{{ form.content.value|default_if_none:'' }}</textarea>
        </div>
        <button type="submit" class="btn btn-primary">저장하기</button>
    </form>
</div>
{% endblock %}

templates/bonvoyage/question_list.html
{% extends 'base.html' %}
{% load bonvoyage_filter %}
{% block content %}
<div class="container my-3">
    <div class="col-2">
        <select class="form-control so">
            <option value="recent" {% if so == 'recent' %}selected{% endif %}>최신순</option>
            <option value="recommend" {% if so == 'recommend' %}selected{% endif %}>추천순</option>
            <option value="popular" {% if so == 'popular' %}selected{% endif %}>인기순</option>
        </select>
    </div>
    <table class="table">
        <thead>
        <tr class="text-center thead-dark">
            <th>번호</th>
            <th>추천</th>
            <th style="width:50%">제목</th>
            <th>글쓴이</th>
            <th>작성일시</th>
        </tr>
        </thead>
        <tbody>
        {% if question_list %}
        {% for question in question_list %}
        <tr class="text-center">
            <td>
                <!-- 번호 = 전체건수 - 시작인덱스 - 현재인덱스 + 1 -->
                {{ question_list.paginator.count|sub:question_list.start_index|sub:forloop.counter0|add:1 }}
            </td>
            <td>
                {% if question.voter.all.count > 0 %}
                <span class="badge badge-warning px-2 py-1">{{ question.voter.all.count }}</span>
                {% endif %}
            </td>
            <td class="text-left">
                <a href="{% url 'bonvoyage:detail' question.id %}" class="text-success">{{ question.subject }}</a>
                {% if question.answer_set.count > 0 %}
                <span class="text-danger small ml-2">{{ question.answer_set.count }}</span>
                {% endif %}
            </td>
            <td>{{ question.author }}</td>
            <td>{{ question.create_date }}</td>
        </tr>
        {% endfor %}
        {% else %}
        <tr>
            <td colspan="3">질문이 없습니다.</td>
        </tr>
        {% endif %}
        </tbody>
    </table>
    <!-- 페이징처리 시작 -->
    <ul class="pagination justify-content-center">
        <!-- 이전페이지 -->
        {% if question_list.has_previous %}
        <li class="page-item">
            <a class="page-link" data-page="{{ question_list.previous_page_number }}" href="#">이전</a>
        </li>
        {% else %}
        <li class="page-item disabled">
            <a class="page-link" tabindex="-1" aria-disabled="true" href="#">이전</a>
        </li>
        {% endif %}
        <!-- 페이지리스트 -->
        {% for page_number in question_list.paginator.page_range %}
        {% if page_number >= question_list.number|add:-5 and page_number <= question_list.number|add:5 %}
            {% if page_number == question_list.number %}
            <li class="page-item active" aria-current="page">
                <a class="page-link" data-page="{{ page_number }}" href="#">{{ page_number }}</a>
            </li>
            {% else %}
            <li class="page-item">
                <a class="page-link" data-page="{{ page_number }}" href="#">{{ page_number }}</a>
            </li>
            {% endif %}
        {% endif %}
        {% endfor %}
        <!-- 다음페이지 -->
        {% if question_list.has_next %}
        <li class="page-item">
            <a class="page-link" data-page="{{ question_list.next_page_number }}" href="#">다음</a>
        </li>
        {% else %}
        <li class="page-item disabled">
            <a class="page-link" tabindex="-1" aria-disabled="true" href="#">다음</a>
        </li>
        {% endif %}
    </ul>
    <!-- 페이징처리 끝 -->
    <a href="{% url 'bonvoyage:question_create' %}" class="btn btn-success">구절 등록하기</a>
</div>
<form id="searchForm" method="get" action="{% url 'index' %}">
    <input type="hidden" id="kw" name="kw" value="{{ kw|default_if_none:'' }}">
    <input type="hidden" id="page" name="page" value="{{ page }}">
    <input type="hidden" id="so" name="so" value="{{ so }}">
</form>
{% endblock %}
{% block script %}
<script type='text/javascript'>
$(document).ready(function(){
    $(".page-link").on('click', function() {
        $("#page").val($(this).data("page"));
        $("#searchForm").submit();
    });

    $("#btn_search").on('click', function() {
        $("#kw").val($(".kw").val());
        $("#page").val(1);  // 검색버튼을 클릭할 경우 1페이지부터 조회한다.
        $("#searchForm").submit();
    });

    $(".so").on('change', function() {
        $("#so").val($(this).val());
        $("#page").val(1);
        $("#searchForm").submit();
    });
});
</script>
{% endblock %}